<a href="https://colab.research.google.com/github/EtBadass/Aulas-FIAP/blob/main/Aulas_fase_1_cap3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algebra linear -> x + 2 = 5 -> x = 3 (Algebra linear = RESOLVER SISTEMAS DE EQUAÇOES LINEARES)

info 1 -- {x + y = 10 -> -3 + y = 10 ------(0,10), (2,8), (-3,13) -- ininitas soluçoes (equaçoes diofantina -> ininitas sol)

info 2 -- {2x - y = 11

$$ \alpha + \beta = 10 $$
$$\pmatrix{}$$
$$\*alpha + \*beta = 10 -sem o *$$

In [ ]:
import numpy as np
import scipy as sc
import sympy as sy

-escalar = numero qualquer (considerado um tensor de ordem 0)

x = 2 (x é um escalar)

-vetor = x,y,etc de um plano cartesiano

[1 2 3]

-matriz = junção de vetores

[[1]
 [2]
 [3]]

In [ ]:
x = 2

In [ ]:
type(x)

int

In [ ]:
x2 = np.array([1,2,3]) # vetor com tres elementos escalares
x3 = np.array([[1],[2],[3]]) # matriz com tres elementos vetores com elementos escalares
x4 = np.array([[1,2,3], [1,2,3], [1,2,3]]) # matriz tradicional

In [ ]:
print(x2)
print()
print(x3)
print()
print(x4)

[1 2 3]

[[1]
 [2]
 [3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
import pandas as pd

In [ ]:
lista = np.array([1,2,3,4,5])

df = pd.DataFrame({'coluna':lista, 'coluna 2': lista}) #{} dicionario

In [ ]:
df['coluna']

0    1
1    2
2    3
3    4
4    5
Name: coluna, dtype: int64

In [ ]:
type(df.coluna)

pandas.core.series.Series

In [ ]:
lista[:1]

array([1])

In [ ]:
x2 + x3 #combinação linear

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
x3 + x4

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
x4 + x4

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [ ]:
x5 = np.array([[1],[2]])

In [ ]:
#multiplicar

#arr1 (x,y) / arr2 (z,w) ---> y = z / arr3 (x, w)

# A.B != B.A

In [ ]:
#np.dot(x3,x4) #aqui y != z da erro

In [ ]:
np.dot(x4,x3) #aqui y = z

array([[14],
       [14],
       [14]])

In [ ]:
x4@x3 #é a mesma coisa

array([[14],
       [14],
       [14]])

In [ ]:
# divisão
# 2.x = 4
# A.X = Y -----> equanção fundamental da algebra linear

In [ ]:
x4/x3

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [ ]:
x3/x4

array([[1.        , 0.5       , 0.33333333],
       [2.        , 1.        , 0.66666667],
       [3.        , 1.5       , 1.        ]])

In [ ]:
#x3/x5 #nao tem a mesma dimenção!!

In [ ]:
1*0

0

In [ ]:
0*1

0

In [ ]:
#1/0  #erro division by zero

In [ ]:
#para os escalares, o 0 na soma e na subtração, é oq chamamos de elemento neutro
#porem, o 1 na multiplicação e na divisão, é o elemento neutro

In [ ]:
zeros = np.zeros(3)

zeros

array([0., 0., 0.])

In [ ]:
zeros = np.zeros((3,3))

zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones = np.ones((3,3))

print(zeros)
print()
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
x4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

$$ A = \pmatrix{a_{00} & a_{01} & a_{02} \\ a_{10} & a_{11} & a_{12} \\ a_{20} & a_{21} & a_{22}}
$$

In [ ]:
id = np.eye(3)

id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
id*x4

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:
x4*1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])